# Pandas Handling Missing Values

## Introduction

In real-world datasets, some values are often missing due to data entry errors, system failures, incomplete surveys, or data collection issues.

These missing values are called **Missing Values** and are represented as:

```python
NaN
```

NaN stands for:

```text
Not a Number
```

Handling missing values is an important step in Data Cleaning and Data Preprocessing because Machine Learning models cannot work properly with missing data.

---

# Why Handle Missing Values?

Missing values can:

* Reduce model accuracy
* Cause errors during analysis
* Produce incorrect results
* Affect machine learning performance

Therefore, missing values must be identified and handled before analysis.

---

### Sample Dataset

In [2]:
import pandas as pd 
import numpy as np 

data = { "Name": ["John", "Alice", "Bob", "David", "Emma"],
        "Age": [25, np.nan, 28, 35, np.nan],
        "Salary": [50000, 60000, np.nan, 70000, 55000], 
        "Department": ["IT", "HR", "Finance", np.nan, "IT"] 
        
      }

df = pd.DataFrame(data)

df

    Name   Age   Salary Department
0   John  25.0  50000.0         IT
1  Alice   NaN  60000.0         HR
2    Bob  28.0      NaN    Finance
3  David  35.0  70000.0        NaN
4   Emma   NaN  55000.0         IT

### Checking Missing Values
isnull()

Used to identify missing values.

In [3]:
df.isnull()

    Name    Age  Salary  Department
0  False  False   False       False
1  False   True   False       False
2  False  False    True       False
3  False  False   False        True
4  False   True   False       False

In [4]:
df.notnull()

   Name    Age  Salary  Department
0  True   True    True        True
1  True  False    True        True
2  True   True   False        True
3  True   True    True       False
4  True  False    True        True

### Count Missing Values

In [5]:
df.isnull().sum()

Name          0
Age           2
Salary        1
Department    1
dtype: int64

### Removing Missing Values
   dropna()

   Removes rows containing missing values.

In [6]:
df.dropna()

   Name   Age   Salary Department
0  John  25.0  50000.0         IT

### Remove Columns And Row with Missing Values


Axis Parameter

axis=0 → Rows

axis=1 → Columns

In [12]:
df.dropna(axis = 0)

   Name   Age   Salary Department
0  John  25.0  50000.0         IT

In [13]:
df.dropna(axis = 1)

    Name
0   John
1  Alice
2    Bob
3  David
4   Emma

### fill with Constant Value

In [ ]:
df["Age"] = df["Age"].fillna(0)
df

    Name   Age   Salary Department
0   John  25.0  50000.0         IT
1  Alice   0.0  60000.0         HR
2    Bob  28.0      NaN    Finance
3  David  35.0  70000.0        NaN
4   Emma   0.0  55000.0         IT

### Fill with Mean

In [23]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

df

    Name   Age   Salary Department
0   John  25.0  50000.0         IT
1  Alice   0.0  60000.0         HR
2    Bob  28.0  58750.0    Finance
3  David  35.0  70000.0        NaN
4   Emma   0.0  55000.0         IT

### Fill with Median

In [26]:
df["Age"] = df["Age"].fillna(df["Age"].median)
df

    Name   Age   Salary Department
0   John  25.0  50000.0         IT
1  Alice   0.0  60000.0         HR
2    Bob  28.0  58750.0    Finance
3  David  35.0  70000.0        NaN
4   Emma   0.0  55000.0         IT

### Fill with Mode

In [28]:
df["Department"] = df["Department"].fillna(
    df["Department"].mode()[0]
)

df

    Name   Age   Salary Department
0   John  25.0  50000.0         IT
1  Alice   0.0  60000.0         HR
2    Bob  28.0  58750.0    Finance
3  David  35.0  70000.0         IT
4   Emma   0.0  55000.0         IT


---

# Mean vs Median vs Mode

| Method | Best Used For                |
| ------ | ---------------------------- |
| Mean   | Numerical Data               |
| Median | Numerical Data with Outliers |
| Mode   | Categorical Data             |

Example:

```text
Age         → Median

Salary      → Mean

Department  → Mode
```


---

# Real Data Science Example

```python
import pandas as pd

df = pd.read_csv("employees.csv")

print(df.isnull().sum())

df["Age"] = df["Age"].fillna(
    df["Age"].median()
)

df["Salary"] = df["Salary"].fillna(
    df["Salary"].mean()
)

df["Department"] = df["Department"].fillna(
    df["Department"].mode()[0]
)
```

This is a common workflow before:

* Data Analysis
* EDA
* Feature Engineering
* Machine Learning

---

# Summary Table

| Function       | Purpose                  |
| -------------- | ------------------------ |
| isnull()       | Check Missing Values     |
| notnull()      | Check Non-Missing Values |
| isnull().sum() | Count Missing Values     |
| dropna()       | Remove Missing Values    |
| fillna()       | Replace Missing Values   |
| mean()         | Average Value            |
| median()       | Middle Value             |
| mode()         | Most Frequent Value      |

---

# Interview Questions

## 1. What are Missing Values?

Missing values are unavailable data points represented as NaN in Pandas.

---

## 2. What does isnull() do?

It identifies missing values in a DataFrame.

---

## 3. What does dropna() do?

It removes rows or columns containing missing values.

---

## 4. What does fillna() do?

It replaces missing values with a specified value.

---

## 5. When should we use Mean, Median, and Mode?

### Mean

Used for numerical data.

### Median

Used for numerical data containing outliers.

### Mode

Used for categorical data.

---

## 6. What is the difference between isnull() and notnull()?

```text
isnull()  → Missing Values

notnull() → Non-Missing Values
```

---

# One-Line Revision

```text
isnull()       → Find Missing Values

dropna()       → Remove Missing Values

fillna()       → Replace Missing Values

mean()         → Average

median()       → Middle Value

mode()         → Most Frequent Value
```