# Pandas GroupBy

## Introduction

The GroupBy operation is used to split data into groups, perform calculations on each group, and combine the results.

It follows the concept:

```text
Split
  ↓
Apply
  ↓
Combine
```

GroupBy is one of the most powerful features in Pandas and is heavily used in:

* Data Analysis
* Business Analytics
* Data Science
* Machine Learning
* Reporting Dashboards

---

# Why Use GroupBy?

Suppose a company wants to know:

* Average salary by department
* Maximum salary by department
* Total salary by department
* Number of employees in each department

GroupBy makes these tasks easy.

---


### Sample Dataset

In [2]:
import numpy as np 
import pandas as pd 

data = {
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'Finance', 'IT'],
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
    'Salary': [50000, 40000, 60000, 70000, 45000, 80000, 55000]
}

df = pd.DataFrame(data)

df

  Department Employee  Salary
0         IT        A   50000
1         HR        B   40000
2         IT        C   60000
3    Finance        D   70000
4         HR        E   45000
5    Finance        F   80000
6         IT        G   55000

### 1. Group By Single Column

In [5]:
print(df.groupby('Department'))

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001BDCEB2FC50>

### 2. Sum of Salary by Department

In [6]:
df.groupby('Department')['Salary'].sum()

Department
Finance    150000
HR          85000
IT         165000
Name: Salary, dtype: int64

### 3. Average Salary by Department

In [7]:
df.groupby('Department')['Salary'].mean()

Department
Finance    75000.0
HR         42500.0
IT         55000.0
Name: Salary, dtype: float64

### 4. Maximum Salary by Department

In [8]:
df.groupby('Department')['Salary'].max()

Department
Finance    80000
HR         45000
IT         60000
Name: Salary, dtype: int64

### 5. Minimum Salary by Department

In [9]:
df.groupby('Department')['Salary'].min()

Department
Finance    70000
HR         40000
IT         50000
Name: Salary, dtype: int64

### 6. Count Employees in Each Department

In [11]:
df.groupby('Department')['Employee'].count()

Department
Finance    2
HR         2
IT         3
Name: Employee, dtype: int64

### 7. Multiple Aggregations

In [12]:
df.groupby('Department')['Salary'].agg(
  ['sum', 'mean', 'min', 'max', 'count']
)

               sum     mean    min    max  count
Department
Finance     150000  75000.0  70000  80000      2
HR           85000  42500.0  40000  45000      2
IT          165000  55000.0  50000  60000      3

### 8. Group By Multiple Columns

In [17]:
data = {
    'Department': ['IT','IT','HR','HR','IT'],
    'Gender': ['M','F','M','F','M'],
    'Salary': [50000,60000,40000,45000,55000]
}

df = pd.DataFrame(data)

df.groupby(['Department','Gender'])['Salary'].mean()

Department  Gender
HR          F         45000.0
            M         40000.0
IT          F         60000.0
            M         52500.0
Name: Salary, dtype: float64

### 9. Using as_index=False

By default, grouped columns become the index.

In [18]:
df.groupby('Department', as_index=False)['Salary'].sum()

  Department  Salary
0         HR   85000
1         IT  165000

#### 10. Using get_group()

In [19]:
grouped  = df.groupby('Department')

grouped.get_group('IT')

  Department Gender  Salary
0         IT      M   50000
1         IT      F   60000
4         IT      M   55000

### Real Data Science Example

     Suppose you have sales data:

In [20]:
sales = {
    'Region': ['North','South','North','East','South'],
    'Sales': [1000,2000,1500,3000,2500]
}

df = pd.DataFrame(sales)

df.groupby('Region')['Sales'].sum()

Region
East     3000
North    2500
South    4500
Name: Sales, dtype: int64



---

# Summary Table

| Function  | Purpose               |
| --------- | --------------------- |
| groupby() | Create Groups         |
| mean()    | Average               |
| sum()     | Total                 |
| min()     | Minimum               |
| max()     | Maximum               |
| count()   | Count Records         |
| agg()     | Multiple Aggregations |

---

# Interview Questions

## 1. What is GroupBy in Pandas?

GroupBy is used to split data into groups and perform calculations on each group.

---

## 2. What is the GroupBy workflow?

```text
Split
 ↓
Apply
 ↓
Combine
```

---

## 3. How do you calculate average salary by department?

```python
df.groupby("Department")["Salary"].mean()
```

---

## 4. What is agg() used for?

It performs multiple aggregation functions at once.

Example:

```python
df.groupby("Department")["Salary"].agg(
    ["mean","min","max","sum"]
)
```

---

## 5. Why is GroupBy important in Data Science?

It helps summarize and analyze data by categories such as departments, regions, products, or customer segments.

---

# One-Line Revision

```text
groupby() → Create Groups

mean()    → Average

sum()     → Total

min()     → Minimum

max()     → Maximum

count()   → Count Records

agg()     → Multiple Aggregations
```